import { StyleSheet } from "react-native";

export const homeStyles = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: "#1b0f14",
  },
  background: {
    ...StyleSheet.absoluteFillObject,
  },
  blob: {
    position: "absolute",
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: "#b45309",
    opacity: 0.18,
    top: -80,
    right: -60,
  },
  blobAlt: {
    position: "absolute",
    width: 280,
    height: 280,
    borderRadius: 140,
    backgroundColor: "#7a1f2b",
    opacity: 0.2,
    bottom: -100,
    left: -70,
  },
  container: {
    backgroundColor: "#fff7f1",
    padding: 20,
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    marginTop: 12,
    paddingBottom: 120,
  },
  topRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 16,
  },
  tag: {
    alignSelf: "flex-start",
    color: "#7a1f2b",
    fontWeight: "700",
    letterSpacing: 2,
    backgroundColor: "#f2e1d5",
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 10,
    marginBottom: 8,
  },
  greetingLabel: {
    fontSize: 13,
    color: "#7b6a5b",
  },
  greetingName: {
    fontSize: 22,
    fontWeight: "800",
    color: "#3b141c",
  },
  statusText: {
    fontSize: 12,
    color: "#9b8b7b",
    marginTop: 2,
  },
  topActions: {
    flexDirection: "row",
    alignItems: "center",
  },
  avatar: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: "#7a1f2b",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 10,
  },
  avatarText: {
    color: "#ffffff",
    fontWeight: "700",
  },
  menuButton: {
    height: 36,
    paddingHorizontal: 10,
    borderRadius: 10,
    backgroundColor: "#fff7f1",
    borderWidth: 1,
    borderColor: "#e8cdbd",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 10,
  },
  menuIcon: {
    color: "#7a1f2b",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1,
  },
  searchRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 14,
  },
  searchInputWrapper: {
    flex: 1,
    backgroundColor: "#ffffff",
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "#e6c9b7",
    shadowColor: "#0f172a",
    shadowOpacity: 0.06,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  searchInput: {
    fontSize: 14,
    color: "#3b141c",
  },
  filterButton: {
    height: 46,
    paddingHorizontal: 14,
    borderRadius: 14,
    backgroundColor: "#7a1f2b",
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 10,
  },
  filterIcon: {
    color: "#ffffff",
    fontSize: 12,
    fontWeight: "700",
    letterSpacing: 1,
  },
  heroRow: {
    paddingRight: 20,
  },
  heroCard: {
    backgroundColor: "#2a1218",
    borderRadius: 22,
    padding: 18,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  heroContent: {
    flex: 1,
    paddingRight: 10,
  },
  heroBadge: {
    alignSelf: "flex-start",
    backgroundColor: "#b45309",
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 10,
    marginBottom: 8,
  },
  heroBadgeText: {
    color: "#ffffff",
    fontWeight: "700",
    fontSize: 10,
    letterSpacing: 1,
  },
  heroTitle: {
    color: "#fff7f1",
    fontSize: 18,
    fontWeight: "800",
  },
  heroSubtitle: {
    color: "#f0d9c7",
    fontSize: 13,
    marginTop: 4,
    marginBottom: 10,
  },
  heroCta: {
    backgroundColor: "#f2e1d5",
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 12,
    alignSelf: "flex-start",
  },
  heroCtaText: {
    color: "#7a1f2b",
    fontWeight: "700",
  },
  heroImage: {
    width: 96,
    height: 96,
    resizeMode: "contain",
  },
  dotsRow: {
    flexDirection: "row",
    justifyContent: "center",
    marginBottom: 10,
  },
  dot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#e8cdbd",
    marginHorizontal: 4,
  },
  dotActive: {
    backgroundColor: "#7a1f2b",
  },
  statsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  statCard: {
    width: "48%",
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 12,
    flexDirection: "row",
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#e8cdbd",
  },
  statIcon: {
    width: 28,
    height: 28,
    resizeMode: "contain",
    marginRight: 10,
  },
  statTitle: {
    fontSize: 13,
    fontWeight: "700",
    color: "#3b141c",
  },
  statSubtitle: {
    fontSize: 11,
    color: "#7b6a5b",
    marginTop: 2,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "800",
    color: "#3b141c",
  },
  resultsHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginTop: 6,
    marginBottom: 8,
  },
  seeAll: {
    color: "#7a1f2b",
    fontWeight: "700",
  },
  categoriesRow: {
    marginBottom: 12,
  },
  categoryChip: {
    marginRight: 16,
    alignItems: "center",
  },
  categoryIconWrap: {
    width: 54,
    height: 54,
    borderRadius: 27,
    backgroundColor: "#ffffff",
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: "#e6c9b7",
    shadowColor: "#0f172a",
    shadowOpacity: 0.08,
    shadowRadius: 8,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  categoryIcon: {
    width: 54,
    height: 54,
    borderRadius: 27,
    resizeMode: "cover",
  },
  categoryActive: {
    borderColor: "#7a1f2b",
  },
  categoryText: {
    color: "#3b141c",
    fontWeight: "600",
    marginTop: 8,
    fontSize: 12,
  },
  categoryTextActive: {
    color: "#7a1f2b",
  },
  error: {
    color: "#dc2626",
    marginBottom: 10,
    textAlign: "center",
  },
  productGridCard: {
    width: "48%",
    backgroundColor: "#ffffff",
    borderRadius: 18,
    padding: 12,
    marginBottom: 14,
    borderWidth: 1,
    borderColor: "#e8cdbd",
    shadowColor: "#0f172a",
    shadowOpacity: 0.06,
    shadowRadius: 6,
    shadowOffset: { width: 0, height: 4 },
    elevation: 2,
  },
  productImageWrapper: {
    backgroundColor: "#f4e8dd",
    borderRadius: 16,
    paddingVertical: 14,
    alignItems: "center",
    marginBottom: 10,
    position: "relative",
    overflow: "hidden",
  },
  discountBadge: {
    position: "absolute",
    top: 8,
    left: 8,
    backgroundColor: "#7a1f2b",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 10,
    zIndex: 1,
  },
  discountText: {
    color: "#ffffff",
    fontWeight: "700",
    fontSize: 10,
    letterSpacing: 1,
  },
  productImage: {
    width: 90,
    height: 110,
    resizeMode: "contain",
  },
  productName: {
    fontSize: 15,
    fontWeight: "700",
    color: "#3b141c",
    marginBottom: 4,
  },
  productMeta: {
    color: "#7b6a5b",
    fontSize: 12,
    marginBottom: 6,
  },
  priceRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  productPrice: {
    fontWeight: "800",
    marginRight: 8,
    color: "#7a1f2b",
  },
  oldPrice: {
    color: "#9b8b7b",
    textDecorationLine: "line-through",
  },
  addButton: {
    backgroundColor: "#7a1f2b",
    paddingVertical: 10,
    borderRadius: 12,
    alignItems: "center",
  },
  addButtonText: {
    color: "#ffffff",
    fontWeight: "700",
  },
  bottomNav: {
    flexDirection: "row",
    justifyContent: "space-around",
    backgroundColor: "#ffffff",
    paddingVertical: 12,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    borderTopWidth: 1,
    borderColor: "#e8cdbd",
  },
  bottomItem: {
    alignItems: "center",
  },
  bottomLabel: {
    fontSize: 12,
    color: "#7b6a5b",
    fontWeight: "600",
  },
  bottomLabelActive: {
    color: "#7a1f2b",
  },
  bottomDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: "transparent",
    marginTop: 4,
  },
  bottomDotActive: {
    backgroundColor: "#7a1f2b",
  },

  welcomeContainer: {
    flex: 1,
    backgroundColor: "#0f172a",
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  welcomeLogo: {
    width: 140,
    height: 140,
    resizeMode: "contain",
    marginBottom: 24,
  },
  welcomeTitle: {
    fontSize: 30,
    fontWeight: "800",
    color: "#ffffff",
    marginBottom: 8,
    textAlign: "center",
  },
  welcomeSubtitle: {
    fontSize: 15,
    color: "#cbd5e1",
    textAlign: "center",
    marginBottom: 40,
    paddingHorizontal: 10,
  },
  welcomeButton: {
    backgroundColor: "#dc2626",
    paddingVertical: 16,
    paddingHorizontal: 40,
    borderRadius: 14,
    elevation: 6,
  },
  welcomeButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "700",
  },
  welcomeFooter: {
    position: "absolute",
    bottom: 20,
    fontSize: 12,
    color: "#94a3b8",
  },

  permissionsContainer: {
    flex: 1,
    backgroundColor: "#0f172a",
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  permissionsIcon: {
    width: 110,
    height: 110,
    resizeMode: "contain",
    marginBottom: 20,
  },
  permissionsTitle: {
    fontSize: 26,
    fontWeight: "800",
    color: "#ffffff",
    marginBottom: 16,
    textAlign: "center",
  },
  permissionsCard: {
    backgroundColor: "#020617",
    borderRadius: 14,
    padding: 20,
    marginBottom: 30,
  },
  permissionsText: {
    fontSize: 14,
    color: "#cbd5e1",
    textAlign: "center",
    marginBottom: 10,
    lineHeight: 20,
  },
  permissionsButton: {
    backgroundColor: "#dc2626",
    paddingVertical: 16,
    paddingHorizontal: 40,
    borderRadius: 14,
    elevation: 6,
  },
  permissionsButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "700",
  },
  permissionsFooter: {
    position: "absolute",
    bottom: 20,
    fontSize: 12,
    color: "#94a3b8",
  },

  benefitsContainer: {
    flex: 1,
    backgroundColor: "#0f172a",
    padding: 24,
  },
  benefitsTitle: {
    fontSize: 26,
    fontWeight: "800",
    color: "#ffffff",
    textAlign: "center",
    marginTop: 20,
  },
  benefitsSubtitle: {
    fontSize: 14,
    color: "#cbd5e1",
    textAlign: "center",
    marginBottom: 30,
  },
  benefitsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  benefitCard: {
    width: "48%",
    backgroundColor: "#020617",
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    alignItems: "center",
  },
  benefitIcon: {
    width: 48,
    height: 48,
    resizeMode: "contain",
    marginBottom: 10,
  },
  benefitTitle: {
    fontSize: 15,
    fontWeight: "700",
    color: "#ffffff",
    marginBottom: 6,
    textAlign: "center",
  },
  benefitText: {
    fontSize: 13,
    color: "#cbd5e1",
    textAlign: "center",
  },
  benefitsButton: {
    backgroundColor: "#dc2626",
    paddingVertical: 16,
    borderRadius: 14,
    alignItems: "center",
    marginTop: 10,
  },
  benefitsButtonText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "700",
  },

  accessContainer: {
    flex: 1,
    backgroundColor: "#0f172a",
    alignItems: "center",
    justifyContent: "center",
    padding: 24,
  },
  accessLogo: {
    width: 120,
    height: 120,
    resizeMode: "contain",
    marginBottom: 20,
  },
  accessTitle: {
    fontSize: 26,
    fontWeight: "800",
    color: "#ffffff",
    marginBottom: 6,
  },
  accessSubtitle: {
    fontSize: 14,
    color: "#cbd5e1",
    textAlign: "center",
    marginBottom: 36,
  },
  accessPrimaryButton: {
    backgroundColor: "#dc2626",
    paddingVertical: 16,
    paddingHorizontal: 40,
    borderRadius: 14,
    width: "100%",
    alignItems: "center",
    marginBottom: 14,
  },
  accessPrimaryText: {
    color: "#ffffff",
    fontSize: 16,
    fontWeight: "700",
  },
  accessSecondaryButton: {
    borderWidth: 1,
    borderColor: "#dc2626",
    paddingVertical: 16,
    paddingHorizontal: 40,
    borderRadius: 14,
    width: "100%",
    alignItems: "center",
  },
  accessSecondaryText: {
    color: "#dc2626",
    fontSize: 16,
    fontWeight: "700",
  },
  accessFooter: {
    position: "absolute",
    bottom: 20,
    fontSize: 12,
    color: "#94a3b8",
  },
});
