import { StyleSheet } from "react-native";

export const loginStyles = StyleSheet.create({
  container: {
    flexGrow: 1,
    backgroundColor: "#1b0f14",
    padding: 22,
    justifyContent: "center",
  },
  background: {
    ...StyleSheet.absoluteFillObject,
  },
  circleTop: {
    position: "absolute",
    width: 260,
    height: 260,
    borderRadius: 130,
    backgroundColor: "#b45309",
    opacity: 0.18,
    top: -110,
    right: -90,
  },
  circleBottom: {
    position: "absolute",
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: "#7a1f2b",
    opacity: 0.2,
    bottom: -80,
    left: -70,
  },
  cardHeader: {
    flexDirection: "row",
    alignItems: "center",
    alignSelf: "stretch",
  },
  logoBadge: {
    width: 54,
    height: 54,
    borderRadius: 16,
    backgroundColor: "#7a1f2b",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  logo: {
    width: 42,
    height: 42,
    resizeMode: "contain",
  },
  brand: {
    color: "#7a1f2b",
    fontWeight: "800",
    fontSize: 18,
    letterSpacing: 0.5,
  },
  brandSub: {
    color: "#8b6a5a",
    fontSize: 12,
    marginTop: 2,
  },
  title: {
    fontSize: 20,
    fontWeight: "700",
    color: "#3b141c",
    marginTop: 14,
    textAlign: "left",
  },
  subtitle: {
    fontSize: 12,
    color: "#7b6a5b",
    marginTop: 4,
    textAlign: "center",
  },
  helper: {
    fontSize: 12,
    color: "#7b6a5b",
    marginTop: 6,
    marginBottom: 12,
    textAlign: "left",
  },
  divider: {
    height: 1,
    backgroundColor: "#edd9c9",
    marginTop: 14,
    marginBottom: 4,
    alignSelf: "stretch",
  },
  card: {
    backgroundColor: "#fff7f1",
    borderRadius: 22,
    padding: 22,
    borderWidth: 1,
    borderColor: "#e8cdbd",
    shadowColor: "#000000",
    shadowOpacity: 0.2,
    shadowRadius: 14,
    shadowOffset: { width: 0, height: 8 },
    elevation: 4,
    alignSelf: "stretch",
  },
  inputRow: {
    width: "100%",
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fffaf6",
    borderRadius: 14,
    borderWidth: 1,
    borderColor: "#e6c9b7",
    paddingHorizontal: 10,
    paddingVertical: 8,
    marginTop: 10,
  },
  inputIcon: {
    width: 30,
    height: 30,
    borderRadius: 10,
    backgroundColor: "#f2e1d5",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 10,
  },
  inputIconText: {
    color: "#7a1f2b",
    fontWeight: "700",
  },
  inputField: {
    flex: 1,
    fontSize: 14,
    color: "#0f172a",
  },
  toggle: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    alignItems: "center",
    justifyContent: "center",
  },
  toggleText: {
    color: "#7a1f2b",
    fontWeight: "700",
    fontSize: 11,
  },
  button: {
    width: "100%",
    backgroundColor: "#7a1f2b",
    paddingVertical: 12,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 16,
  },
  buttonDisabled: {
    opacity: 0.6,
  },
  buttonText: {
    color: "#ffffff",
    fontWeight: "700",
    fontSize: 15,
  },
  error: {
    color: "#dc2626",
    fontSize: 13,
    marginTop: 8,
    textAlign: "center",
  },
  linkContainer: {
    marginTop: 16,
    alignItems: "center",
  },
  linkText: {
    color: "#7a1f2b",
    fontSize: 14,
    fontWeight: "600",
  },
});
