import { StyleSheet } from "react-native";

export const productDetailStyles = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: "#1b0f14",
  },
  container: {
    padding: 20,
    paddingBottom: 140,
  },
  headerRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  backButton: {
    backgroundColor: "#fff7f1",
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#e8cdbd",
  },
  backText: {
    color: "#7a1f2b",
    fontWeight: "700",
    fontSize: 12,
  },
  headerTag: {
    backgroundColor: "#7a1f2b",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 10,
  },
  headerTagText: {
    color: "#fff7f1",
    fontWeight: "700",
    fontSize: 11,
    letterSpacing: 1,
  },
  heroCard: {
    backgroundColor: "#2a1218",
    borderRadius: 22,
    padding: 18,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  heroImage: {
    width: 180,
    height: 220,
    resizeMode: "contain",
  },
  detailCard: {
    backgroundColor: "#fff7f1",
    borderRadius: 22,
    padding: 20,
    borderWidth: 1,
    borderColor: "#e8cdbd",
  },
  name: {
    fontSize: 22,
    fontWeight: "800",
    color: "#3b141c",
  },
  category: {
    marginTop: 4,
    color: "#7b6a5b",
    fontSize: 13,
  },
  priceRow: {
    flexDirection: "row",
    alignItems: "center",
    marginTop: 12,
    marginBottom: 12,
  },
  price: {
    fontSize: 20,
    fontWeight: "800",
    color: "#7a1f2b",
    marginRight: 10,
  },
  oldPrice: {
    color: "#9b8b7b",
    textDecorationLine: "line-through",
  },
  metaRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 14,
  },
  metaPill: {
    flex: 1,
    backgroundColor: "#fffaf6",
    borderRadius: 12,
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: "#e6c9b7",
    alignItems: "center",
    marginRight: 8,
  },
  metaPillLast: {
    marginRight: 0,
  },
  metaLabel: {
    fontSize: 10,
    color: "#7b6a5b",
    textTransform: "uppercase",
  },
  metaValue: {
    fontSize: 14,
    fontWeight: "700",
    color: "#3b141c",
    marginTop: 4,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: "800",
    color: "#7a1f2b",
    marginBottom: 6,
  },
  description: {
    color: "#5f4a3c",
    lineHeight: 20,
    fontSize: 13,
  },
  footer: {
    position: "absolute",
    left: 0,
    right: 0,
    bottom: 0,
    padding: 16,
    backgroundColor: "#1b0f14",
    borderTopWidth: 1,
    borderColor: "#3b141c",
  },
  addButton: {
    backgroundColor: "#7a1f2b",
    borderRadius: 14,
    paddingVertical: 14,
    alignItems: "center",
  },
  addButtonText: {
    color: "#fff7f1",
    fontWeight: "700",
  },
  emptyCard: {
    marginTop: 140,
    marginHorizontal: 20,
    backgroundColor: "#fff7f1",
    padding: 20,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#e8cdbd",
    alignItems: "center",
  },
  emptyTitle: {
    color: "#3b141c",
    fontWeight: "700",
    marginBottom: 12,
  },
});
