import { StyleSheet } from "react-native";

export const profileStyles = StyleSheet.create({
  page: {
    flex: 1,
    backgroundColor: "#f4ede4",
  },
  background: {
    ...StyleSheet.absoluteFillObject,
  },
  blobTop: {
    position: "absolute",
    top: -80,
    right: -30,
    width: 220,
    height: 220,
    borderRadius: 110,
    backgroundColor: "#d98032",
    opacity: 0.18,
  },
  blobBottom: {
    position: "absolute",
    bottom: 100,
    left: -70,
    width: 240,
    height: 240,
    borderRadius: 120,
    backgroundColor: "#7a4d2a",
    opacity: 0.12,
  },
  container: {
    paddingHorizontal: 18,
    paddingTop: 18,
    paddingBottom: 36,
  },
  headerRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 18,
  },
  backButton: {
    backgroundColor: "#fffaf4",
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderWidth: 1,
    borderColor: "#e3d7ca",
  },
  backText: {
    color: "#6d4222",
    fontSize: 12,
    fontWeight: "800",
    textTransform: "uppercase",
  },
  title: {
    color: "#332117",
    fontSize: 22,
    fontWeight: "800",
  },
  reloadButton: {
    paddingHorizontal: 8,
    paddingVertical: 10,
  },
  reloadText: {
    color: "#8b5e34",
    fontSize: 12,
    fontWeight: "700",
  },
  heroCard: {
    backgroundColor: "#fffaf4",
    borderRadius: 28,
    padding: 18,
    borderWidth: 1,
    borderColor: "#eadfd2",
    shadowColor: "#6f4e37",
    shadowOpacity: 0.08,
    shadowRadius: 16,
    shadowOffset: { width: 0, height: 8 },
    elevation: 3,
    marginBottom: 18,
  },
  heroContent: {
    flexDirection: "row",
    alignItems: "center",
  },
  avatarWrap: {
    marginRight: 14,
  },
  avatarImage: {
    width: 74,
    height: 74,
    borderRadius: 24,
  },
  avatarFallback: {
    width: 74,
    height: 74,
    borderRadius: 24,
    backgroundColor: "#d98032",
    alignItems: "center",
    justifyContent: "center",
  },
  avatarText: {
    color: "#fffaf4",
    fontSize: 28,
    fontWeight: "800",
  },
  heroTextBlock: {
    flex: 1,
  },
  nameText: {
    color: "#2e1f16",
    fontSize: 20,
    fontWeight: "800",
  },
  emailText: {
    color: "#7f6856",
    fontSize: 13,
    marginTop: 3,
  },
  roleChip: {
    alignSelf: "flex-start",
    backgroundColor: "#f7efe4",
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
    marginTop: 10,
  },
  roleChipText: {
    color: "#8b5e34",
    fontWeight: "700",
    fontSize: 12,
  },
  metaRow: {
    flexDirection: "row",
    marginTop: 16,
  },
  metaPill: {
    flex: 1,
    backgroundColor: "#f8f1e8",
    borderRadius: 18,
    padding: 12,
    marginRight: 10,
  },
  metaLabel: {
    color: "#9a7f67",
    fontSize: 11,
    textTransform: "uppercase",
    fontWeight: "700",
    marginBottom: 4,
  },
  metaValue: {
    color: "#3c281b",
    fontSize: 13,
    fontWeight: "700",
  },
  statsSection: {
    marginBottom: 18,
  },
  sectionTag: {
    color: "#90745d",
    fontSize: 11,
    fontWeight: "800",
    letterSpacing: 0.8,
    marginBottom: 10,
  },
  statCard: {
    width: 126,
    backgroundColor: "#fffaf4",
    borderRadius: 20,
    padding: 14,
    marginRight: 12,
    borderWidth: 1,
    borderColor: "#eadfd2",
  },
  statValue: {
    color: "#bf6a25",
    fontSize: 22,
    fontWeight: "800",
  },
  statLabel: {
    color: "#332117",
    fontSize: 13,
    fontWeight: "700",
    marginTop: 6,
  },
  statSubtitle: {
    color: "#90745d",
    fontSize: 11,
    marginTop: 4,
  },
  feedbackRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#6d4222",
    borderRadius: 18,
    paddingVertical: 12,
    marginBottom: 18,
  },
  feedbackText: {
    color: "#fffaf4",
    marginLeft: 10,
    fontWeight: "700",
  },
  errorCard: {
    backgroundColor: "#fff2ef",
    borderRadius: 20,
    padding: 16,
    borderWidth: 1,
    borderColor: "#f0c6bc",
    marginBottom: 18,
  },
  errorText: {
    color: "#9f2f1d",
    fontWeight: "700",
    marginBottom: 10,
  },
  retryButton: {
    alignSelf: "flex-start",
    backgroundColor: "#9f2f1d",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  retryText: {
    color: "#fffaf4",
    fontWeight: "700",
  },
  sectionBlock: {
    marginBottom: 18,
  },
  menuCard: {
    backgroundColor: "#fffaf4",
    borderRadius: 24,
    borderWidth: 1,
    borderColor: "#eadfd2",
    overflow: "hidden",
  },
  menuRow: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingVertical: 15,
  },
  menuRowBorder: {
    borderBottomWidth: 1,
    borderBottomColor: "#f0e5d9",
  },
  menuBadge: {
    width: 38,
    height: 38,
    borderRadius: 12,
    backgroundColor: "#f4e5d3",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 12,
  },
  menuBadgeText: {
    color: "#8b5e34",
    fontSize: 12,
    fontWeight: "800",
  },
  menuTextWrap: {
    flex: 1,
    paddingRight: 12,
  },
  menuTitle: {
    color: "#2e1f16",
    fontSize: 15,
    fontWeight: "700",
  },
  menuSubtitle: {
    color: "#8e7764",
    fontSize: 12,
    marginTop: 4,
  },
  switchWrap: {
    minWidth: 56,
    alignItems: "flex-end",
  },
  trailingWrap: {
    flexDirection: "row",
    alignItems: "center",
  },
  trailingText: {
    color: "#8e7764",
    fontSize: 12,
    fontWeight: "700",
    marginRight: 8,
  },
  chevron: {
    color: "#b29780",
    fontSize: 18,
    fontWeight: "700",
  },
  logoutButton: {
    backgroundColor: "#6d4222",
    borderRadius: 18,
    paddingVertical: 16,
    alignItems: "center",
    marginTop: 4,
  },
  logoutText: {
    color: "#fffaf4",
    fontSize: 15,
    fontWeight: "800",
  },
});
